# Generated by Django 4.1.7 on 2023-06-04 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_votes_song_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='song_query',
        ),
    ]
