# Generated by Django 4.1.7 on 2023-06-12 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_remove_votes_song_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='song_id',
            new_name='uri',
        ),
    ]
