# Generated by Django 4.1.7 on 2023-06-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='search_query',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
