# Generated by Django 4.1.7 on 2023-06-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room_search_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='search_query',
        ),
    ]
