# Generated by Django 4.1.7 on 2023-06-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_room_search_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
