# Generated by Django 4.1.7 on 2023-06-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_room_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_time',
            field=models.IntegerField(default=0),
        ),
    ]
